### ISSUE TITLE
We should have a Travis build

### ISSUE THREAD

**Issue by SebastianSchildt** [GENIVI/vss-tools#12] opened 2020-08-18 17:53 UTC
We should have a Travis build for this, which tries to use the tools with the current VSS specification

**Comment by gunnarx** [comment] 2020-08-18 18:08
I'm going back on vacation but... a work in progress:

https://github.com/gunnarx/vss-tools/blob/master/.travis.yml
https://travis-ci.org/github/gunnarx/vss-tools/builds/719048177

It's complaining about the f' string syntax, so still some python2/python3 problem I'm guessing?
The travis file explicitly shows python --version to be 3.6 but once you get into executing the scripts there's something...  Please check.

**Comment by gunnarx** [comment] 2020-08-18 18:13
By the way I'm not 100% clear on this line:
```
cd vss-tools && python setup.py -q install && cd ..
```
(taken from .travis.yml in https://github.com/genivi/vehicle_signal_specification)
Is it really needed to do a python setup install?  Or could it just be run from within the directory as-is?  I'm usually more comfortable with the latter generally so there's no need to "install" but I realize that users might want to fully "install" the tools and/or that there might be a python best practices.

I suppose if we should support the setup/install officially then we should test that however.  
So I would guess my question is : Please give your opinion if setup.py is our official strategy or not.

And of course, let's fix the above.

**Comment by gunnarx** [comment] 2020-08-24 10:43
Travis build fails because vspec.py", line 248 uses python3 syntax, but python2 is being called.
```
    node.value = f'$include${load_flat_model.include_index}'
```

_When running in Travis..._, python 2 is being called.  Here is the full situation inside of the Travis execution environment, the way it is set up now at least:
```
$ python3 --version
Python 3.6.7
$ python2 --version
Python 2.7.12
$ /usr/bin/python --version
Python 2.7.12
$ /usr/bin/env python --version
Python 3.6.7
$ python --version
Python 3.6.7
```

Several programs call `#!/usr/bin/python` at the top.   `ocf/vspec2ocf.py`, `vspec2cnative.py` and a few others then import vspec.py and then the syntax error occurs.

The issue is that this path, which is normally the right way, ends up calling python 2.  This might be different now but Travis uses quite an old Ubuntu version as its basis.

What's the recommended solution do you think?  I might suggest we could change all our programs to:  `#!/usr/bin/env python` ?

**Comment by gunnarx** [comment] 2020-08-26 13:50
It seems part of the issue might be that the xenial version of Travis was after switching to python3 using version 3.5 but f'strings were introduced from version 3.6 forward.

Sent PR #19 . Please see .travis.yml and usage of env for final resolution of the above problems.

**Comment by gunnarx** [comment] 2020-08-26 13:51
Closing, since further commentary can happen on #19.

**Closed by gunnarx** 2020-08-26 13:51 UTC
