### ISSUE TITLE
Parsing into typesafe structure

### ISSUE THREAD

**Issue by Floix** [GENIVI/vss-tools#5] opened 2020-05-31 16:59 UTC
VSS tools parsing result currently parses into a Dictionary structure. This has some disadvantages over using a typesafe (as far as it gets in python) tree structure.
1.) Missing documentation and autocompletion during development time. 
2.) Missing checks and validations (e.g., various ways to express a unit like l, liters, liter, Liter, LITER)
3.) Implementation of traversal operations during generation steps.

We'd like to introduce anytree (https://anytree.readthedocs.io/en/latest/) along with entity classes and enumerations for VSS Nodes. We'll benefit from this library traversal functions (Post-Order, Pre-Order, Level-Order traversal), document our node structure (meta-model) as code annotations and simplify development.

Sponsor: @danielwilms 
Presented at VSS call 27.04.2020

**Comment by danielwilms** [comment] 2020-06-01 06:22
Reference to [issue 150](../../vehicle_signal_specification/issues/150) in the VSS repo

**Comment by Floix** [comment] 2020-06-03 08:53
From https://github.com/GENIVI/vehicle_signal_specification/issues/150 this PR fixes:
* Node types: one of branch, attribute, sensor, actuator, stream
* Data types, we have a similar list
* Units: we have a similar list, but this one might change with new signals.

**Comment by gunnarx** [comment] 2020-06-03 14:09
I'll probably see the advantages better when starting to use Anytree traversal functions.

I'd just point out that implementing checks such as number 2) seems possible to achieve without turning the strings to classes and enums.  Just implement the checks to enforce some convention I mean.
 
> 2.) Missing checks and validations (e.g., various ways to express a unit like l, liters, liter, Liter, LITER)

**Comment by gunnarx** [comment] 2020-08-04 17:07
We merged because wanted most of the code available.  This is still not explained however:
https://github.com/GENIVI/vss-tools/pull/7#discussion_r447283118

**Comment by gunnarx** [comment] 2020-08-04 17:09
I'm closing this since the issue is done but opening a new one to explain the UINT/INT discrepancy.

**Closed** 2020-08-04 17:09 UTC
